### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by kigiri** [01-edu/01-edu-api#1]
https://github.com/LEEDASILVA/01-edu-api/blob/bed5b585c51bcb38446a2f6f1b5e4fa075f91e36/index.js#L23-L36

this could be done using async interation, and also add error handleling:
```js
async (res) => {
   if (res.statusCode !== 200) return reject(Error(res.statusMessage))
   try {
     const body = []
     for await (const chunk of res) {
       body.push(chunk)
     }
     resolve(JSON.parse(Buffer.concat(body).toString()))
   } catch (err) {
     reject(err)
   }
 }
```

**Comment by LEEDASILVA** [comment]
sorry for just seeing this now, i did the changes and looks good
