### ISSUE TITLE
Is it possible to make mutations?

### ISSUE THREAD

**Issue by Dias1c** [01-edu/01-edu-api#2]
Hello, I want to write mutation which creates record for many users with same message but i have error with that. So I think it cause we have readonly access. 

**Where I can see which access I have?**
https://public.01-edu.org/docs/db/db-authorization
![image](https://user-images.githubusercontent.com/52798029/183868778-0c03e9dd-b300-4fdb-b4d3-8b47e8c298e5.png)

If you look at the platform, there are only 4 roles (role `[user]` is default, without roles), and I have `[admin]` and `[campus-admin]`. And according to the picture above, in theory I have the opportunity to make mutations because I have the role of `[admin]`.
![image](https://user-images.githubusercontent.com/52798029/183869759-13e3d3b9-399d-4a55-9214-51133547efe5.png)

**Maybe I wrote the wrong request?**
Here is an example:
```graphql
# Example of permanent ban user
mutation{
  insert_record(
    objects: {
      authorId: 600,
      userId: 600,
      banEndAt: null,
      message: "example"
    }
  ){
    returning{
      id
    }
  }
}
```
It shows error: `"Mutations are disabled as this is using live data"`

**Is there also a way to automatically give 1-type records to several users in 1 click?**
Doing this manually on the platform is inconvenient. 
> What if admin want to create 30 record with same message.

**Comment by kigiri** [comment]
this would be a feature request, the API support is read only
